

const overAllPopulation =  [{
    "id":"1",
    "County": "Mifflin",
    "Population": 46167,
    "Population MOE": 128,
    "Uninsured": 7130,
    "Uninsured MOE": 676,
    "Uninsured Pct": "15.4%",
    "Uninsured Pct MOE": "1.5%"
  },
  {
    "id":"2",
    "County": "Clearfield",
    "Population": 76508,
    "Population MOE": 432,
    "Uninsured": 7838,
    "Uninsured MOE": 644,
    "Uninsured Pct": "10.2%",
    "Uninsured Pct MOE": "0.8%"
  },{
    "id":"3",
    "County": "Beaver",
    "Population": 168629,
    "Population MOE": 222,
    "Uninsured": 12481,
    "Uninsured MOE": 843,
    "Uninsured Pct": "7.4%",
    "Uninsured Pct MOE": "0.5%",
  }]

const populationPerAge = [{
    "id":"1",
    "County": "Mifflin",
    "Population - Under 18 years": 10657,
    "Population - Under 18 years MOE": 49,
    "Population - Under 18 years - Uninsured": 2032,
    "Population - Under 18 years - Uninsured MOE": 385,
    "Population - Under 18 years - Uninsured Pct": "19.1%",
    "Population - Under 18 years - Uninsured Pct MOE": "3.6%",
    "Population - 18 to 64 years": 26868,
    "Population - 18 to 64 years MOE": 91,
    "Population - 18 to 64 years - Uninsured": 4980,
    "Population - 18 to 64 years - Uninsured MOE": 420,
    "Population - 18 to 64 years - Uninsured Pct": "18.5%",
    "Population - 18 to 64 years - Uninsured Pct MOE": "1.6%",
    "Population - 65 years and older": 8642,
    "Population - 65 years and older MOE": 107,
    "Population - 65 years and older - Uninsured": 118,
    "Population - 65 years and older - Uninsured MOE": 63,
    "Population - 65 years and older - Uninsured Pct": "1.4%",
    "Population - 65 years and older - Uninsured Pct MOE": "0.7%",
    "Population - 19 to 25 years": 3424,
    "Population - 19 to 25 years MOE": 185,
    "Population - 19 to 25 years - Uninsured": 876,
    "Population - 19 to 25 years - Uninsured MOE": 174,
    "Population - 19 to 25 years - Uninsured Pct": "25.6%",
    "Population - 19 to 25 years - Uninsured Pct MOE": "4.9%"
  },
  {
    "id":"2",
    "County": "Clearfield",
    "Population - Under 18 years": 15642,
    "Population - Under 18 years MOE": 99,
    "Population - Under 18 years - Uninsured": 606,
    "Population - Under 18 years - Uninsured MOE": 166,
    "Population - Under 18 years - Uninsured Pct": "3.9%",
    "Population - Under 18 years - Uninsured Pct MOE": "1.1%",
    "Population - 18 to 64 years": 46820,
    "Population - 18 to 64 years MOE": 356,
    "Population - 18 to 64 years - Uninsured": 7197,
    "Population - 18 to 64 years - Uninsured MOE": 572,
    "Population - 18 to 64 years - Uninsured Pct": "15.4%",
    "Population - 18 to 64 years - Uninsured Pct MOE": "1.2%",
    "Population - 65 years and older": 14046,
    "Population - 65 years and older MOE": 201,
    "Population - 65 years and older - Uninsured": 35,
    "Population - 65 years and older - Uninsured MOE": 33,
    "Population - 65 years and older - Uninsured Pct": "0.2%",
    "Population - 65 years and older - Uninsured Pct MOE": "0.2%",
    "Population - 19 to 25 years": 5871,
    "Population - 19 to 25 years MOE": 270,
    "Population - 19 to 25 years - Uninsured": 1290,
    "Population - 19 to 25 years - Uninsured MOE": 228,
    "Population - 19 to 25 years - Uninsured Pct": "22%",
    "Population - 19 to 25 years - Uninsured Pct MOE": "3.4%"
    },
    {
      "id":"3",
      "County": "Beaver",
      "Population - Under 18 years": 34004,
      "Population - Under 18 years MOE": 20,
      "Population - Under 18 years - Uninsured": 987,
      "Population - Under 18 years - Uninsured MOE": 215,
      "Population - Under 18 years - Uninsured Pct": "2.9%",
      "Population - Under 18 years - Uninsured Pct MOE": "0.6%",
      "Population - 18 to 64 years": 102861,
      "Population - 18 to 64 years MOE": 186,
      "Population - 18 to 64 years - Uninsured": 11464,
      "Population - 18 to 64 years - Uninsured MOE": 783,
      "Population - 18 to 64 years - Uninsured Pct": "11.1%",
      "Population - 18 to 64 years - Uninsured Pct MOE": "0.8%",
      "Population - 65 years and older": 31764,
      "Population - 65 years and older MOE": 188,
      "Population - 65 years and older - Uninsured": 30,
      "Population - 65 years and older - Uninsured MOE": 35,
      "Population - 65 years and older - Uninsured Pct": "0.1%",
      "Population - 65 years and older - Uninsured Pct MOE": "0.1%",
      "Population - 19 to 25 years": 13245,
      "Population - 19 to 25 years MOE": 348,
      "Population - 19 to 25 years - Uninsured": 2225,
      "Population - 19 to 25 years - Uninsured MOE": 219,
      "Population - 19 to 25 years - Uninsured Pct": "16.8%",
      "Population - 19 to 25 years - Uninsured Pct MOE": "1.7%"
    }]

const populationPerGender = [{
    "id":"1",
    "County": "Mifflin",
    "Male": 22834,
    "Male MOE": 112,
    "Male - Uninsured": 3678,
    "Male - Uninsured MOE": 377,
    "Male - Uninsured Pct": "16.1%",
    "Male - Uninsured Pct MOE": "1.6%",
    "Female": 23333,
    "Female MOE": 127,
    "Female - Uninsured": 3452,
    "Female - Uninsured MOE": 373,
    "Female - Uninsured Pct": "14.8%",
    "Female - Uninsured Pct MOE": "1.6%"
  },{
    "id":"2",
    "County": "Clearfield",
     "Male": 38060,
    "Male MOE": 337,
    "Male - Uninsured": 4304,
    "Male - Uninsured MOE": 419,
    "Male - Uninsured Pct": "11.3%",
    "Male - Uninsured Pct MOE": "1.1%",
    "Female": 38448,
    "Female MOE": 207,
    "Female - Uninsured": 3534,
    "Female - Uninsured MOE": 366,
    "Female - Uninsured Pct": "9.2%",
    "Female - Uninsured Pct MOE": "0.9%"
  },{
    "id":"3",
    "County": "Beaver",
    "Male": 81530,
    "Male MOE": 190,
    "Male - Uninsured": 6704,
    "Male - Uninsured MOE": 471,
    "Male - Uninsured Pct": "8.2%",
    "Male - Uninsured Pct MOE": "0.6%",
    "Female": 87099,
    "Female MOE": 184,
    "Female - Uninsured": 5777,
    "Female - Uninsured MOE": 536,
    "Female - Uninsured Pct": "6.6%",
    "Female - Uninsured Pct MOE": "0.6%",
  }]

const populationPerRace = [{
    "id":"1",
    "County": "Mifflin",
    "Race - One Race": 75964,
    "Race - One Race MOE": 402,
    "Race - One Race - Uninsured": 7777,
    "Race - One Race - Uninsured MOE": 645,
    "Race - One Race - Uninsured Pct": "10.2%",
    "Race - One Race - Uninsured Pct MOE": "0.8%",
    "Race - One Race - White": 75369,
    "Race - One Race - White MOE": 355,
    "Race - One Race - White - Uninsured": 7680,
    "Race - One Race - White - Uninsured MOE": 636,
    "Race - One Race - White - Uninsured Pct": "10.2%",
    "Race - One Race - White - Uninsured Pct MOE": "0.8%",
    "Race - One Race - Black or African American": 74,
    "Race - One Race - Black or African American MOE": 135,
    "Race - One Race - Black or African American - Uninsured": 4,
    "Race - One Race - Black or African American - Uninsured MOE": 15,
    "Race - One Race - Black or African American - Uninsured Pct": "5.4%",
    "Race - One Race - Black or African American - Uninsured Pct MOE": "60.1%",
    "Race - One Race - American Indian and Alaska Native": 77,
    "Race - One Race - American Indian and Alaska Native MOE": 36,
    "Race - One Race - American Indian and Alaska Native - Uninsured": 16,
    "Race - One Race - American Indian and Alaska Native - Uninsured MOE": 18,
    "Race - One Race - American Indian and Alaska Native - Uninsured Pct": "20.8%",
    "Race - One Race - American Indian and Alaska Native - Uninsured Pct MOE": "22.5%",
    "Race - One Race - Asian": 370,
    "Race - One Race - Asian MOE": 96,
    "Race - One Race - Asian - Uninsured": 37,
    "Race - One Race - Asian - Uninsured MOE": 36,
    "Race - One Race - Asian - Uninsured Pct": "10%",
    "Race - One Race - Asian - Uninsured Pct MOE": "9.6%",
    "Race - One Race - Native Hawaiian and Other Pacific Islander": 0,
    "Race - One Race - Native Hawaiian and Other Pacific Islander MOE": 24,
    "Race - One Race - Native Hawaiian and Other Pacific Islander - Uninsured": 0,
    "Race - One Race - Native Hawaiian and Other Pacific Islander - Uninsured MOE": 24,
    "Race - One Race - Native Hawaiian and Other Pacific Islander - Uninsured Pct": "",
    "Race - One Race - Native Hawaiian and Other Pacific Islander - Uninsured Pct MOE": "",
    "Race - One Race - Some other race": 74,
    "Race - One Race - Some other race MOE": 60,
    "Race - One Race - Some other race - Uninsured": 40,
    "Race - One Race - Some other race - Uninsured MOE": 50,
    "Race - One Race - Some other race - Uninsured Pct": "54.1%",
    "Race - One Race - Some other race - Uninsured Pct MOE": "36.6%",
    "Race - Two or more races": 544,
    "Race - Two or more races MOE": 165,
    "Race - Two or more races - Uninsured": 61,
    "Race - Two or more races - Uninsured MOE": 52,
    "Race - Two or more races - Uninsured Pct": "11.2%",
    "Race - Two or more races - Uninsured Pct MOE": "8.2%",
    "White, not Hispanic or Latino": 74402,
    "White, not Hispanic or Latino MOE": 286,
    "White, not Hispanic or Latino - Uninsured": 7467,
    "White, not Hispanic or Latino - Uninsured MOE": 607,
    "White, not Hispanic or Latino - Uninsured Pct": "10%",
    "White, not Hispanic or Latino - Uninsured Pct MOE": "0.8%",
    "Hispanic or Latino (of any race)": 1090,
    "Hispanic or Latino (of any race) MOE": 198,
    "Hispanic or Latino (of any race) - Uninsured": 275,
    "Hispanic or Latino (of any race) - Uninsured MOE": 205,
    "Hispanic or Latino (of any race) - Uninsured Pct": "25.2%",
    "Hispanic or Latino (of any race) - Uninsured Pct MOE": "17.6%"
  },
  {
    "id":"2",
    "County": "Clearfield",
    "Race - One Race": 75964,
    "Race - One Race MOE": 402,
    "Race - One Race - Uninsured": 7777,
    "Race - One Race - Uninsured MOE": 645,
    "Race - One Race - Uninsured Pct": "10.2%",
    "Race - One Race - Uninsured Pct MOE": "0.8%",
    "Race - One Race - White": 75369,
    "Race - One Race - White MOE": 355,
    "Race - One Race - White - Uninsured": 7680,
    "Race - One Race - White - Uninsured MOE": 636,
    "Race - One Race - White - Uninsured Pct": "10.2%",
    "Race - One Race - White - Uninsured Pct MOE": "0.8%",
    "Race - One Race - Black or African American": 74,
    "Race - One Race - Black or African American MOE": 135,
    "Race - One Race - Black or African American - Uninsured": 4,
    "Race - One Race - Black or African American - Uninsured MOE": 15,
    "Race - One Race - Black or African American - Uninsured Pct": "5.4%",
    "Race - One Race - Black or African American - Uninsured Pct MOE": "60.1%",
    "Race - One Race - American Indian and Alaska Native": 77,
    "Race - One Race - American Indian and Alaska Native MOE": 36,
    "Race - One Race - American Indian and Alaska Native - Uninsured": 16,
    "Race - One Race - American Indian and Alaska Native - Uninsured MOE": 18,
    "Race - One Race - American Indian and Alaska Native - Uninsured Pct": "20.8%",
    "Race - One Race - American Indian and Alaska Native - Uninsured Pct MOE": "22.5%",
    "Race - One Race - Asian": 370,
    "Race - One Race - Asian MOE": 96,
    "Race - One Race - Asian - Uninsured": 37,
    "Race - One Race - Asian - Uninsured MOE": 36,
    "Race - One Race - Asian - Uninsured Pct": "10%",
    "Race - One Race - Asian - Uninsured Pct MOE": "9.6%",
    "Race - One Race - Native Hawaiian and Other Pacific Islander": 0,
    "Race - One Race - Native Hawaiian and Other Pacific Islander MOE": 24,
    "Race - One Race - Native Hawaiian and Other Pacific Islander - Uninsured": 0,
    "Race - One Race - Native Hawaiian and Other Pacific Islander - Uninsured MOE": 24,
    "Race - One Race - Native Hawaiian and Other Pacific Islander - Uninsured Pct": "",
    "Race - One Race - Native Hawaiian and Other Pacific Islander - Uninsured Pct MOE": "",
    "Race - One Race - Some other race": 74,
    "Race - One Race - Some other race MOE": 60,
    "Race - One Race - Some other race - Uninsured": 40,
    "Race - One Race - Some other race - Uninsured MOE": 50,
    "Race - One Race - Some other race - Uninsured Pct": "54.1%",
    "Race - One Race - Some other race - Uninsured Pct MOE": "36.6%",
    "Race - Two or more races": 544,
    "Race - Two or more races MOE": 165,
    "Race - Two or more races - Uninsured": 61,
    "Race - Two or more races - Uninsured MOE": 52,
    "Race - Two or more races - Uninsured Pct": "11.2%",
    "Race - Two or more races - Uninsured Pct MOE": "8.2%",
    "White, not Hispanic or Latino": 74402,
    "White, not Hispanic or Latino MOE": 286,
    "White, not Hispanic or Latino - Uninsured": 7467,
    "White, not Hispanic or Latino - Uninsured MOE": 607,
    "White, not Hispanic or Latino - Uninsured Pct": "10%",
    "White, not Hispanic or Latino - Uninsured Pct MOE": "0.8%",
    "Hispanic or Latino (of any race)": 1090,
    "Hispanic or Latino (of any race) MOE": 198,
    "Hispanic or Latino (of any race) - Uninsured": 275,
    "Hispanic or Latino (of any race) - Uninsured MOE": 205,
    "Hispanic or Latino (of any race) - Uninsured Pct": "25.2%",
    "Hispanic or Latino (of any race) - Uninsured Pct MOE": "17.6%"
  },{
    "id":"3",
    "County": "Beaver",
    "Race - One Race": 165135,
    "Race - One Race MOE": 418,
    "Race - One Race - Uninsured": 12204,
    "Race - One Race - Uninsured MOE": 833,
    "Race - One Race - Uninsured Pct": "7.4%",
    "Race - One Race - Uninsured Pct MOE": "0.5%",
    "Race - One Race - White": 153530,
    "Race - One Race - White MOE": 285,
    "Race - One Race - White - Uninsured": 10471,
    "Race - One Race - White - Uninsured MOE": 722,
    "Race - One Race - White - Uninsured Pct": "6.8%",
    "Race - One Race - White - Uninsured Pct MOE": "0.5%",
    "Race - One Race - Black or African American": 10017,
    "Race - One Race - Black or African American MOE": 383,
    "Race - One Race - Black or African American - Uninsured": 1457,
    "Race - One Race - Black or African American - Uninsured MOE": 262,
    "Race - One Race - Black or African American - Uninsured Pct": "14.5%",
    "Race - One Race - Black or African American - Uninsured Pct MOE": "2.6%",
    "Race - One Race - American Indian and Alaska Native": 151,
    "Race - One Race - American Indian and Alaska Native MOE": 147,
    "Race - One Race - American Indian and Alaska Native - Uninsured": 21,
    "Race - One Race - American Indian and Alaska Native - Uninsured MOE": 20,
    "Race - One Race - American Indian and Alaska Native - Uninsured Pct": "13.9%",
    "Race - One Race - American Indian and Alaska Native - Uninsured Pct MOE": "17.9%",
    "Race - One Race - Asian": 929,
    "Race - One Race - Asian MOE": 91,
    "Race - One Race - Asian - Uninsured": 141,
    "Race - One Race - Asian - Uninsured MOE": 96,
    "Race - One Race - Asian - Uninsured Pct": "15.2%",
    "Race - One Race - Asian - Uninsured Pct MOE": "10.5%",
    "Race - One Race - Native Hawaiian and Other Pacific Islander": 19,
    "Race - One Race - Native Hawaiian and Other Pacific Islander MOE": 20,
    "Race - One Race - Native Hawaiian and Other Pacific Islander - Uninsured": 11,
    "Race - One Race - Native Hawaiian and Other Pacific Islander - Uninsured MOE": 16,
    "Race - One Race - Native Hawaiian and Other Pacific Islander - Uninsured Pct": "57.9%",
    "Race - One Race - Native Hawaiian and Other Pacific Islander - Uninsured Pct MOE": "57.9%",
    "Race - One Race - Some other race": 489,
    "Race - One Race - Some other race MOE": 154,
    "Race - One Race - Some other race - Uninsured": 103,
    "Race - One Race - Some other race - Uninsured MOE": 106,
    "Race - One Race - Some other race - Uninsured Pct": "21.1%",
    "Race - One Race - Some other race - Uninsured Pct MOE": "19.3%",
    "Race - Two or more races": 3494,
    "Race - Two or more races MOE": 359,
    "Race - Two or more races - Uninsured": 277,
    "Race - Two or more races - Uninsured MOE": 104,
    "Race - Two or more races - Uninsured Pct": "7.9%",
    "Race - Two or more races - Uninsured Pct MOE": "2.8%",
    "White, not Hispanic or Latino": 152112,
    "White, not Hispanic or Latino MOE": 227,
    "White, not Hispanic or Latino - Uninsured": 10407,
    "White, not Hispanic or Latino - Uninsured MOE": 722,
    "White, not Hispanic or Latino - Uninsured Pct": "6.8%",
    "White, not Hispanic or Latino - Uninsured Pct MOE": "0.5%",
    "Hispanic or Latino (of any race)": 2222,
    "Hispanic or Latino (of any race) MOE": 14,
    "Hispanic or Latino (of any race) - Uninsured": 179,
    "Hispanic or Latino (of any race) - Uninsured MOE": 112,
    "Hispanic or Latino (of any race) - Uninsured Pct": "8.1%",
    "Hispanic or Latino (of any race) - Uninsured Pct MOE": "5.1%"
  }]

const populationPerIncome = [{
    "id":"1",
    "County": "Mifflin",
    "Household Income": 76355,
    "Household Income MOE": 437,
    "Household Income - Uninsured": 7825,
    "Household Income - Uninsured MOE": 647,
    "Household Income - Uninsured Pct": "10.2%",
    "Household Income - Uninsured Pct MOE": "0.8%",
    "Household Income - Under $25,000": 15993,
    "Household Income - Under $25,000 MOE": 868,
    "Household Income - Under $25,000 - Uninsured": 2532,
    "Household Income - Under $25,000 - Uninsured MOE": 378,
    "Household Income - Under $25,000 - Uninsured Pct": "15.8%",
    "Household Income - Under $25,000 - Uninsured Pct MOE": "2%",
    "Household Income - $25,000 to $49,999": 21525,
    "Household Income - $25,000 to $49,999 MOE": 1060,
    "Household Income - $25,000 to $49,999 - Uninsured": 2456,
    "Household Income - $25,000 to $49,999 - Uninsured MOE": 368,
    "Household Income - $25,000 to $49,999 - Uninsured Pct": "11.4%",
    "Household Income - $25,000 to $49,999 - Uninsured Pct MOE": "1.5%",
    "Household Income - $50,000 to $74,999": 17681,
    "Household Income - $50,000 to $74,999 MOE": 1107,
    "Household Income - $50,000 to $74,999 - Uninsured": 1488,
    "Household Income - $50,000 to $74,999 - Uninsured MOE": 341,
    "Household Income - $50,000 to $74,999 - Uninsured Pct": "8.4%",
    "Household Income - $50,000 to $74,999 - Uninsured Pct MOE": "1.8%",
    "Household Income - $75,000 to $99,999": 9902,
    "Household Income - $75,000 to $99,999 MOE": 839,
    "Household Income - $75,000 to $99,999 - Uninsured": 692,
    "Household Income - $75,000 to $99,999 - Uninsured MOE": 247,
    "Household Income - $75,000 to $99,999 - Uninsured Pct": "7%",
    "Household Income - $75,000 to $99,999 - Uninsured Pct MOE": "2.4%",
    "Household Income - $100,000 and over": 11254,
    "Household Income - $100,000 and over MOE": 967,
    "Household Income - $100,000 and over - Uninsured": 657,
    "Household Income - $100,000 and over - Uninsured MOE": 173,
    "Household Income - $100,000 and over - Uninsured Pct": "5.8%",
    "Household Income - $100,000 and over - Uninsured Pct MOE": "1.5%",
    "Ratio of Income to Poverty Level": 76142,
    "Ratio of Income to Poverty Level MOE": 448,
    "Ratio of Income to Poverty Level - Uninsured": 7838,
    "Ratio of Income to Poverty Level - Uninsured MOE": 644,
    "Ratio of Income to Poverty Level - Uninsured Pct": "10.3%",
    "Ratio of Income to Poverty Level - Uninsured Pct MOE": "0.8%",
    "Ratio of Income to Poverty Level - Under 1.38 of poverty": 18270,
    "Ratio of Income to Poverty Level - Under 1.38 of poverty MOE": 1134,
    "Ratio of Income to Poverty Level - Under 1.38 of poverty - Uninsured": 3346,
    "Ratio of Income to Poverty Level - Under 1.38 of poverty - Uninsured MOE": 446,
    "Ratio of Income to Poverty Level - Under 1.38 of poverty - Uninsured Pct": "18.3%",
    "Ratio of Income to Poverty Level - Under 1.38 of poverty - Uninsured Pct MOE": "2.1%",
    "Ratio of Income to Poverty Level - 1.38 to 1.99 of poverty": 10820,
    "Ratio of Income to Poverty Level - 1.38 to 1.99 of poverty MOE": 809,
    "Ratio of Income to Poverty Level - 1.38 to 1.99 of poverty - Uninsured": 1189,
    "Ratio of Income to Poverty Level - 1.38 to 1.99 of poverty - Uninsured MOE": 237,
    "Ratio of Income to Poverty Level - 1.38 to 1.99 of poverty - Uninsured Pct": "11%",
    "Ratio of Income to Poverty Level - 1.38 to 1.99 of poverty - Uninsured Pct MOE": "2%",
    "Ratio of Income to Poverty Level - 2.00 of poverty and over": 47052,
    "Ratio of Income to Poverty Level - 2.00 of poverty and over MOE": 1183,
    "Ratio of Income to Poverty Level - 2.00 of poverty and over - Uninsured": 3303,
    "Ratio of Income to Poverty Level - 2.00 of poverty and over - Uninsured MOE": 375,
    "Ratio of Income to Poverty Level - 2.00 of poverty and over - Uninsured Pct": "7%",
    "Ratio of Income to Poverty Level - 2.00 of poverty and over - Uninsured Pct MOE": "0.8%"
  },{
    "id":"2",
    "County": "Clearfield",
    "Household Income": 76355,
    "Household Income MOE": 437,
    "Household Income - Uninsured": 7825,
    "Household Income - Uninsured MOE": 647,
    "Household Income - Uninsured Pct": "10.2%",
    "Household Income - Uninsured Pct MOE": "0.8%",
    "Household Income - Under $25,000": 15993,
    "Household Income - Under $25,000 MOE": 868,
    "Household Income - Under $25,000 - Uninsured": 2532,
    "Household Income - Under $25,000 - Uninsured MOE": 378,
    "Household Income - Under $25,000 - Uninsured Pct": "15.8%",
    "Household Income - Under $25,000 - Uninsured Pct MOE": "2%",
    "Household Income - $25,000 to $49,999": 21525,
    "Household Income - $25,000 to $49,999 MOE": 1060,
    "Household Income - $25,000 to $49,999 - Uninsured": 2456,
    "Household Income - $25,000 to $49,999 - Uninsured MOE": 368,
    "Household Income - $25,000 to $49,999 - Uninsured Pct": "11.4%",
    "Household Income - $25,000 to $49,999 - Uninsured Pct MOE": "1.5%",
    "Household Income - $50,000 to $74,999": 17681,
    "Household Income - $50,000 to $74,999 MOE": 1107,
    "Household Income - $50,000 to $74,999 - Uninsured": 1488,
    "Household Income - $50,000 to $74,999 - Uninsured MOE": 341,
    "Household Income - $50,000 to $74,999 - Uninsured Pct": "8.4%",
    "Household Income - $50,000 to $74,999 - Uninsured Pct MOE": "1.8%",
    "Household Income - $75,000 to $99,999": 9902,
    "Household Income - $75,000 to $99,999 MOE": 839,
    "Household Income - $75,000 to $99,999 - Uninsured": 692,
    "Household Income - $75,000 to $99,999 - Uninsured MOE": 247,
    "Household Income - $75,000 to $99,999 - Uninsured Pct": "7%",
    "Household Income - $75,000 to $99,999 - Uninsured Pct MOE": "2.4%",
    "Household Income - $100,000 and over": 11254,
    "Household Income - $100,000 and over MOE": 967,
    "Household Income - $100,000 and over - Uninsured": 657,
    "Household Income - $100,000 and over - Uninsured MOE": 173,
    "Household Income - $100,000 and over - Uninsured Pct": "5.8%",
    "Household Income - $100,000 and over - Uninsured Pct MOE": "1.5%",
    "Ratio of Income to Poverty Level": 76142,
    "Ratio of Income to Poverty Level MOE": 448,
    "Ratio of Income to Poverty Level - Uninsured": 7838,
    "Ratio of Income to Poverty Level - Uninsured MOE": 644,
    "Ratio of Income to Poverty Level - Uninsured Pct": "10.3%",
    "Ratio of Income to Poverty Level - Uninsured Pct MOE": "0.8%",
    "Ratio of Income to Poverty Level - Under 1.38 of poverty": 18270,
    "Ratio of Income to Poverty Level - Under 1.38 of poverty MOE": 1134,
    "Ratio of Income to Poverty Level - Under 1.38 of poverty - Uninsured": 3346,
    "Ratio of Income to Poverty Level - Under 1.38 of poverty - Uninsured MOE": 446,
    "Ratio of Income to Poverty Level - Under 1.38 of poverty - Uninsured Pct": "18.3%",
    "Ratio of Income to Poverty Level - Under 1.38 of poverty - Uninsured Pct MOE": "2.1%",
    "Ratio of Income to Poverty Level - 1.38 to 1.99 of poverty": 10820,
    "Ratio of Income to Poverty Level - 1.38 to 1.99 of poverty MOE": 809,
    "Ratio of Income to Poverty Level - 1.38 to 1.99 of poverty - Uninsured": 1189,
    "Ratio of Income to Poverty Level - 1.38 to 1.99 of poverty - Uninsured MOE": 237,
    "Ratio of Income to Poverty Level - 1.38 to 1.99 of poverty - Uninsured Pct": "11%",
    "Ratio of Income to Poverty Level - 1.38 to 1.99 of poverty - Uninsured Pct MOE": "2%",
    "Ratio of Income to Poverty Level - 2.00 of poverty and over": 47052,
    "Ratio of Income to Poverty Level - 2.00 of poverty and over MOE": 1183,
    "Ratio of Income to Poverty Level - 2.00 of poverty and over - Uninsured": 3303,
    "Ratio of Income to Poverty Level - 2.00 of poverty and over - Uninsured MOE": 375,
    "Ratio of Income to Poverty Level - 2.00 of poverty and over - Uninsured Pct": "7%",
    "Ratio of Income to Poverty Level - 2.00 of poverty and over - Uninsured Pct MOE": "0.8%"
  },{
    "id":"3",
    "County": "Beaver",
    "Household Income": 166808,
    "Household Income MOE": 385,
    "Household Income - Uninsured": 12419,
    "Household Income - Uninsured MOE": 848,
    "Household Income - Uninsured Pct": "7.4%",
    "Household Income - Uninsured Pct MOE": "0.5%",
    "Household Income - Under $25,000": 28214,
    "Household Income - Under $25,000 MOE": 1342,
    "Household Income - Under $25,000 - Uninsured": 3429,
    "Household Income - Under $25,000 - Uninsured MOE": 457,
    "Household Income - Under $25,000 - Uninsured Pct": "12.2%",
    "Household Income - Under $25,000 - Uninsured Pct MOE": "1.5%",
    "Household Income - $25,000 to $49,999": 38390,
    "Household Income - $25,000 to $49,999 MOE": 1624,
    "Household Income - $25,000 to $49,999 - Uninsured": 3949,
    "Household Income - $25,000 to $49,999 - Uninsured MOE": 445,
    "Household Income - $25,000 to $49,999 - Uninsured Pct": "10.3%",
    "Household Income - $25,000 to $49,999 - Uninsured Pct MOE": "1.1%",
    "Household Income - $50,000 to $74,999": 33411,
    "Household Income - $50,000 to $74,999 MOE": 1800,
    "Household Income - $50,000 to $74,999 - Uninsured": 2494,
    "Household Income - $50,000 to $74,999 - Uninsured MOE": 423,
    "Household Income - $50,000 to $74,999 - Uninsured Pct": "7.5%",
    "Household Income - $50,000 to $74,999 - Uninsured Pct MOE": "1.2%",
    "Household Income - $75,000 to $99,999": 27674,
    "Household Income - $75,000 to $99,999 MOE": 1519,
    "Household Income - $75,000 to $99,999 - Uninsured": 1257,
    "Household Income - $75,000 to $99,999 - Uninsured MOE": 255,
    "Household Income - $75,000 to $99,999 - Uninsured Pct": "4.5%",
    "Household Income - $75,000 to $99,999 - Uninsured Pct MOE": "0.9%",
    "Household Income - $100,000 and over": 39119,
    "Household Income - $100,000 and over MOE": 1475,
    "Household Income - $100,000 and over - Uninsured": 1290,
    "Household Income - $100,000 and over - Uninsured MOE": 258,
    "Household Income - $100,000 and over - Uninsured Pct": "3.3%",
    "Household Income - $100,000 and over - Uninsured Pct MOE": "0.6%",
    "Ratio of Income to Poverty Level": 167217,
    "Ratio of Income to Poverty Level MOE": 375,
    "Ratio of Income to Poverty Level - Uninsured": 12440,
    "Ratio of Income to Poverty Level - Uninsured MOE": 844,
    "Ratio of Income to Poverty Level - Uninsured Pct": "7.4%",
    "Ratio of Income to Poverty Level - Uninsured Pct MOE": "0.5%",
    "Ratio of Income to Poverty Level - Under 1.38 of poverty": 29733,
    "Ratio of Income to Poverty Level - Under 1.38 of poverty MOE": 1332,
    "Ratio of Income to Poverty Level - Under 1.38 of poverty - Uninsured": 4154,
    "Ratio of Income to Poverty Level - Under 1.38 of poverty - Uninsured MOE": 461,
    "Ratio of Income to Poverty Level - Under 1.38 of poverty - Uninsured Pct": "14%",
    "Ratio of Income to Poverty Level - Under 1.38 of poverty - Uninsured Pct MOE": "1.4%",
    "Ratio of Income to Poverty Level - 1.38 to 1.99 of poverty": 18903,
    "Ratio of Income to Poverty Level - 1.38 to 1.99 of poverty MOE": 1200,
    "Ratio of Income to Poverty Level - 1.38 to 1.99 of poverty - Uninsured": 2239,
    "Ratio of Income to Poverty Level - 1.38 to 1.99 of poverty - Uninsured MOE": 339,
    "Ratio of Income to Poverty Level - 1.38 to 1.99 of poverty - Uninsured Pct": "11.8%",
    "Ratio of Income to Poverty Level - 1.38 to 1.99 of poverty - Uninsured Pct MOE": "1.7%",
    "Ratio of Income to Poverty Level - 2.00 of poverty and over": 118581,
    "Ratio of Income to Poverty Level - 2.00 of poverty and over MOE": 1605,
    "Ratio of Income to Poverty Level - 2.00 of poverty and over - Uninsured": 6047,
    "Ratio of Income to Poverty Level - 2.00 of poverty and over - Uninsured MOE": 509,
    "Ratio of Income to Poverty Level - 2.00 of poverty and over - Uninsured Pct": "5.1%",
    "Ratio of Income to Poverty Level - 2.00 of poverty and over - Uninsured Pct MOE": "0.4%"
  }]

export {
  overAllPopulation, populationPerAge, populationPerGender, populationPerRace, populationPerIncome
}
/*,
{
  "ageWisePopulation":{
    "Population - Under 18 years": 10657,
    "Population - Under 18 years MOE": 49,
    "Population - Under 18 years - Uninsured": 2032,
    "Population - Under 18 years - Uninsured MOE": 385,
    "Population - Under 18 years - Uninsured Pct": "19.1%",
    "Population - Under 18 years - Uninsured Pct MOE": "3.6%",
    "Population - 18 to 64 years": 26868,
    "Population - 18 to 64 years MOE": 91,
    "Population - 18 to 64 years - Uninsured": 4980,
    "Population - 18 to 64 years - Uninsured MOE": 420,
    "Population - 18 to 64 years - Uninsured Pct": "18.5%",
    "Population - 18 to 64 years - Uninsured Pct MOE": "1.6%",
    "Population - 65 years and older": 8642,
    "Population - 65 years and older MOE": 107,
    "Population - 65 years and older - Uninsured": 118,
    "Population - 65 years and older - Uninsured MOE": 63,
    "Population - 65 years and older - Uninsured Pct": "1.4%",
    "Population - 65 years and older - Uninsured Pct MOE": "0.7%",
    "Population - 19 to 25 years": 3424,
    "Population - 19 to 25 years MOE": 185,
    "Population - 19 to 25 years - Uninsured": 876,
    "Population - 19 to 25 years - Uninsured MOE": 174,
    "Population - 19 to 25 years - Uninsured Pct": "25.6%",
    "Population - 19 to 25 years - Uninsured Pct MOE": "4.9%"
  }
},
{
  "genderPopulation": {
    "Male": 22834,
    "Male MOE": 112,
    "Male - Uninsured": 3678,
    "Male - Uninsured MOE": 377,
    "Male - Uninsured Pct": "16.1%",
    "Male - Uninsured Pct MOE": "1.6%",
    "Female": 23333,
    "Female MOE": 127,
    "Female - Uninsured": 3452,
    "Female - Uninsured MOE": 373,
    "Female - Uninsured Pct": "14.8%",
    "Female - Uninsured Pct MOE": "1.6%"
  }
}
]
}*/